### ISSUE TITLE
missing file or sum

### ISSUE THREAD

**Issue by idkmanjustgetmeout** [OrbyyOrbinaut/FNF-Weekly-Public#1]
### What is your question?

where's the preload folder at, like that's the only thing it's telling me, it's just gone

![the](https://github.com/user-attachments/assets/37477831-eb8f-4be8-a4be-793adb0b4607)

**Comment by OrbyyOrbinaut** [comment]
This is how I find out I fucked up the repo. oooopsss

**Comment by OrbyyOrbinaut** [comment]
Going to fix reaaaallll quickkkk

**Comment by OrbyyOrbinaut** [comment]
Ok hopefully should be fixed, if its not then tomorrow it should be completely good since we plan on dropping a patch tomorrow

**Comment by idkmanjustgetmeout** [comment]
oh alr cool, just do that first and ill see if it's there 🙏
